services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9991:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:yw6BR9k5FinsLSVQXaeKFNeWkGTU5sR+jwci/WvAzN0=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=vuln_db
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: vuln_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
