services:
  app:
    volumes:
      - ./app:/var/www/html/app:delegated
      - ./bootstrap:/var/www/html/bootstrap:delegated
      - ./config:/var/www/html/config:delegated
      - ./database:/var/www/html/database:delegated
      - ./resources:/var/www/html/resources:delegated
      - ./routes:/var/www/html/routes:delegated
      - ./scripts:/var/www/html/scripts:delegated
      - ./storage:/var/www/html/storage:delegated
      - ./tests:/var/www/html/tests:delegated
      - ./vendor:/var/www/html/vendor:delegated
      - ./.env:/var/www/html/.env

  db:
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
