name: BeaverHealth CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Run Composer Install
        run: composer install -n --prefer-dist

      - name: Build and Start Containers for CI
        run: ./vendor/bin/sail -f docker-compose.ci.yaml up -d --build

      - name: Wait for Database
        run: |
          counter=0
          until ./vendor/bin/sail -f docker-compose.ci.yaml exec db mysqladmin ping --silent; do
            echo "Waiting for database..."
            sleep 2
            counter=$((counter+1))
            if [ $counter -gt 30 ]; then
              echo "Database did not become ready in time."
              exit 1
            fi
          done

      - name: Run Database Migrations
        run: ./vendor/bin/sail -f docker-compose.ci.yaml exec app php artisan migrate

      - name: Test Database Connection via PDO
        run: ./vendor/bin/sail -f docker-compose.ci.yaml exec app php -r "try { new PDO('mysql:host=db;port=3306;dbname=vuln_db', 'admin', 'password'); echo 'Success'; } catch (Exception \$e) { echo 'Failure -- ' . \$e->getMessage(); }"

      - name: Show App Container Logs
        run: ./vendor/bin/sail -f docker-compose.ci.yaml logs app

      - name: Show DB Container Logs
        run: ./vendor/bin/sail -f docker-compose.ci.yaml logs db

      - name: Run Laravel Tests
        run: ./vendor/bin/sail -f docker-compose.ci.yaml exec app php artisan test
