name: BeaverHealth CI

on:
  push:
    branches:
      - master
      - cr-setupCI
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2


      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          php-version: '8.2'
          extensions: ctype, dom, fileinfo, filter, hash, json, libxml, mbstring, openssl, pcre, phar, reflection, session, simplexml, tokenizer, xml, xmlwriter, lib-pcre
          coverage: none

      - name: Run Composer Install
        run: composer install -n --prefer-dist

      - name: Run Laravel Application
        run: vendor/bin/sail up -d --build
